name: Deploy to Azure Blue-Green

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Staging
      run: |
        az webapp config container set --name quicktill-prod --resource-group rg-quicktill --slot staging --docker-custom-image-name reginald001/quicktill-demo:latest --docker-registry-server-url https://index.docker.io
        az webapp restart --name quicktill-prod --resource-group rg-quicktill --slot staging

    - name: Health Check Staging
      run: |
        sleep 60
        curl --fail https://quicktill-prod-staging-fvhwa3cgfkcpf5q6.southafricanorth-01.azurewebsites.net/

    - name: Swap to Production
      run: |
        az webapp deployment slot swap --name quicktill-prod --resource-group rg-quicktill --slot staging --target-slot production
