name: Deploy to Azure - Straight to Prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Prod to New Docker Image
      run: |
        az webapp config container set --name quicktill-prod --resource-group rg-quicktill --docker-custom-image-name reginald001/quicktill-demo:latest --docker-registry-server-url https://index.docker.io
        az webapp restart --name quicktill-prod --resource-group rg-quicktill

    - name: Done
      run: echo "Deployed to https://quicktill-prod.azurewebsites.net"
